// app/components/Home.vue
<template>
  <section
    id="home"
    class="min-h-screen relative overflow-hidden bg-deepBlue pt-10 px-7"
  >
    <!-- Background com gradiente animado -->
    <div
      class="absolute inset-0 bg-gradient-to-br from-deepBlue via-navBlack to-deepBlue"
    >
      <div class="absolute inset-0 opacity-10">
        <div
          class="absolute top-1/4 left-1/4 w-96 h-96 bg-mainTheme rounded-full mix-blend-screen filter blur-3xl opacity-20 animate-pulse"
        ></div>
        <div
          class="absolute bottom-1/4 right-1/4 w-96 h-96 bg-secondaryTheme rounded-full mix-blend-screen filter blur-3xl opacity-20 animate-pulse delay-1000"
        ></div>
      </div>
    </div>

    <!-- Container principal -->
    <div
      class="relative z-10 min-h-screen flex flex-col lg:flex-row items-center justify-center px-4 sm:px-6 lg:px-8 pt-24 pb-12"
    >
      <!-- Coluna esquerda - Conteúdo textual -->
      <div class="lg:w-1/2 lg:pr-12 mb-12 lg:mb-0">
        <div v-motion="animations.slideUp" class="max-w-2xl">
          <!-- Badge de profissional -->
          <div
            v-motion="animations.scaleIn"
            class="inline-flex items-center gap-2 bg-gradient-to-r from-mainTheme/20 to-secondaryTheme/20 border border-mainTheme/30 px-4 py-2 rounded-full mb-6"
          >
            <Icon name="lucide:award" class="w-4 h-4 text-secondaryTheme" />
            <span class="text-sm font-medium text-white/80"
              >Personal Trainer Certificado</span
            >
          </div>

          <!-- Título principal -->
          <h1
            v-motion="animations.slideUp"
            class="text-center lg:text-left text-4xl sm:text-5xl space-x-3 lg:text-6xl xl:text-7xl font-bold leading-tight mb-4"
          >
            <span class="gradient-text2 lg:block">Talles</span>
            <span class="gradient-text lg:block">Furtado</span>
          </h1>

          <!-- Subtítulo -->
          <div v-motion="animations.fadeIn" class="mb-6">
            <div class="flex items-center gap-3 mb-2">
              <Icon
                name="lucide:dumbbell"
                class="w-6 h-6 text-secondaryTheme"
              />
              <h2 class="text-xl sm:text-2xl lg:text-3xl font-bold text-white">
                Especialista em Hipertrofia e Emagrecimento
              </h2>
            </div>

            <!-- Texto rotativo com transição -->
            <div class="h-8 overflow-hidden">
              <transition name="text-rotate" mode="out-in">
                <p
                  :key="currentTextIndex"
                  class="text-lg text-center lg:text-left sm:text-xl text-mainTheme font-semibold"
                >
                  {{ texts[currentTextIndex] }}
                </p>
              </transition>
            </div>
          </div>

          <!-- Descrição -->
          <p
            v-motion="animations.slideUp"
            class="text-white/80 text-base sm:text-lg leading-relaxed mb-8"
          >
            <strong>Bacharel em Educação Física</strong>, atleta de
            fisiculturismo e praticante há mais de <strong>10 anos</strong>.
            Dedico minha carreira a transformar vidas através do esporte,
            combinando ciência, experiência prática e acompanhamento
            personalizado.
          </p>

          <!-- Estatísticas -->
          <div
            v-motion="animations.slideUp"
            class="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-8"
          >
            <div
              v-for="(stat, index) in stats"
              :key="stat.label"
              v-motion="staggerAnimations.scaleIn(index)"
              class="text-center bg-navBlack/50 backdrop-blur-sm rounded-lg p-4 border border-white/10"
            >
              <div class="text-2xl font-bold text-mainTheme mb-1">
                {{ stat.value }}
              </div>
              <div class="text-xs text-white/70">{{ stat.label }}</div>
            </div>
          </div>

          <!-- Botões de ação -->
          <div
            v-motion="animations.slideUp"
            class="flex flex-col sm:flex-row gap-4"
          >
            <!-- Botão para ver planos -->
            <a
              href="#planos"
              class="group flex items-center justify-center gap-3 bg-gradient-to-r from-mainTheme to-blue-600 hover:from-blue-500 hover:to-mainTheme text-white font-bold py-4 px-8 rounded-xl transition-all duration-300 shadow-lg shadow-mainTheme/30"
            >
              <span>Ver Planos</span>
              <Icon
                name="lucide:arrow-right"
                class="w-5 h-5 group-hover:translate-x-1 transition-transform"
              />
            </a>

            <!-- Botão do WhatsApp -->
            <a
              href="https://api.whatsapp.com/send/?phone=558198955665&text&type=phone_number&app_absent=0"
              target="_blank"
              rel="noopener noreferrer"
              class="group flex items-center justify-center gap-3 bg-gradient-to-r from-green-600 to-green-500 hover:from-green-500 hover:to-green-400 text-white font-bold py-4 px-8 rounded-xl transition-all duration-300 border border-green-500/30"
            >
              <Icon name="logos:whatsapp-icon" class="text-2xl" />
              <span>Fale no WhatsApp</span>
            </a>
          </div>
        </div>
      </div>

      <!-- Coluna direita - Imagem -->
      <div class="lg:w-1/2 flex justify-center items-center">
        <div v-motion="animations.scaleIn" class="relative">
          <!-- Moldura decorativa -->
          <div
            class="absolute inset-0 bg-gradient-to-r from-mainTheme to-secondaryTheme rounded-full blur-2xl opacity-20 animate-pulse"
          ></div>
          <div
            class="absolute -inset-4 border-2 border-mainTheme/30 rounded-full animate-spin-slow"
          ></div>

          <!-- Imagem principal -->
          <div v-motion="animations.scaleIn" class="relative z-10">
            <NuxtImg
              src="/img/Img_Hero/profile2.png"
              alt="Talles Furtado - Personal Trainer"
              sizes="sm:350px lg:450px"
              class="w-[280px] sm:w-[350px] lg:w-[450px] rounded-2xl shadow-2xl shadow-mainTheme/30 border-4 border-white/10"
              format="webp"
              :modifiers="{ quality: 85 }"
            />
          </div>

          <!-- Card flutuante - Experiência -->
          <div
            v-motion="animations.slideLeft"
            class="absolute -bottom-6 -left-6 bg-navBlack/80 backdrop-blur-sm border border-white/10 rounded-xl p-4 shadow-xl"
          >
            <div class="flex items-center gap-3">
              <div
                class="w-10 h-10 rounded-full bg-mainTheme/20 flex items-center justify-center"
              >
                <Icon name="lucide:dumbbell" class="w-5 h-5 text-mainTheme" />
              </div>
              <div>
                <div class="text-white font-bold">+10 anos</div>
                <div class="text-white/60 text-xs">Experiência</div>
              </div>
            </div>
          </div>

          <!-- Card flutuante - Campeonatos -->
          <div
            v-motion="animations.slideLeft"
            class="absolute -top-6 -right-6 bg-navBlack/80 backdrop-blur-sm border border-white/10 rounded-xl p-4 shadow-xl"
          >
            <div class="flex items-center gap-3">
              <div
                class="w-10 h-10 rounded-full bg-secondaryTheme/20 flex items-center justify-center"
              >
                <Icon name="lucide:award" class="w-5 h-5 text-secondaryTheme" />
              </div>
              <div>
                <div class="text-white font-bold">2x</div>
                <div class="text-white/60 text-xs">Campeão</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Indicador de scroll -->
    <div
      v-motion="animations.fadeIn"
      class="absolute bottom-8 left-1/2 transform -translate-x-1/2"
    >
      <a
        href="#formacao"
        class="flex flex-col items-center text-white/60 hover:text-mainTheme transition-colors duration-300"
      >
        <span class="text-sm mb-2">Saiba mais</span>
        <div v-motion="animations.slideUp" class="animate-bounce">
          <Icon name="lucide:chevron-down" class="w-6 h-6" />
        </div>
      </a>
    </div>
  </section>
</template>

<script setup lang="ts">
// Dados para o texto rotativo
const currentTextIndex = ref(0);
const texts = [
  "Transformando vidas",
  "Resultados garantidos",
  "Metodologia comprovada",
  "Disciplina e evolução",
];

// Dados para estatísticas
const stats = [
  { value: "10+", label: "Anos de Experiência" },
  { value: "2x", label: "Campeão Mens Physique" },
  { value: "100%", label: "Satisfação dos alunos" },
];

// Intervalo para rotacionar textos
let interval: ReturnType<typeof setInterval>;

onMounted(() => {
  interval = setInterval(() => {
    currentTextIndex.value = (currentTextIndex.value + 1) % texts.length;
  }, 3000);
});

onUnmounted(() => {
  if (interval) clearInterval(interval);
});
</script>

// src/components/Home.tsx
"use client";

import { useState, useEffect } from "react";
import Image from "next/image";
import { motion } from "motion/react";
import {
  slideUp,
  scaleIn,
  fadeUp,
} from "@/components/animatedComponents/variants";
import { FiAward, FiChevronDown, FiArrowRight } from "react-icons/fi";
import { FaDumbbell } from "react-icons/fa";
import { FaWhatsapp } from "react-icons/fa";

export default function Home() {
  const [currentTextIndex, setCurrentTextIndex] = useState(0);
  const texts = [
    "Transformando vidas",
    "Resultados garantidos",
    "Metodologia comprovada",
    "Disciplina e evolução",
  ];

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentTextIndex((prev) => (prev + 1) % texts.length);
    }, 3000);
    return () => clearInterval(interval);
  }, [texts.length]);

  const stats = [
    { value: "10+", label: "Anos de Experiência" },
    { value: "2x", label: "Campeão Mens Physique" },
    { value: "100%", label: "Satisfação dos alunos" },
  ];

  return (
    <section className="bg-deepBlue relative flex min-h-screen items-center overflow-hidden px-7 pt-10">
      {/* Fundo animado */}
      <div className="from-deepBlue via-navBlack to-deepBlue absolute inset-0 bg-gradient-to-br">
        <div className="absolute inset-0 opacity-10">
          <div className="bg-mainTheme absolute top-1/4 left-1/4 h-96 w-96 animate-pulse rounded-full opacity-20 mix-blend-screen blur-3xl filter" />
          <div className="bg-secondaryTheme absolute right-1/4 bottom-1/4 h-96 w-96 animate-pulse rounded-full opacity-20 mix-blend-screen blur-3xl filter delay-1000" />
        </div>
      </div>

      <div className="relative z-10 mx-auto flex w-full max-w-7xl flex-col items-center justify-center gap-12 py-12 lg:flex-row">
        {/* Coluna esquerda */}
        <div className="space-y-8 lg:w-1/2">
          <motion.div variants={slideUp} initial="hidden" animate="visible">
            <span className="from-mainTheme/20 to-secondaryTheme/20 border-mainTheme/30 inline-flex items-center gap-2 rounded-full border bg-gradient-to-r px-4 py-2 text-sm font-medium text-white/80">
              <FiAward className="text-secondaryTheme" />
              Personal Trainer Certificado
            </span>
          </motion.div>

          <motion.h1
            variants={slideUp}
            initial="hidden"
            animate="visible"
            className="text-4xl leading-tight font-bold sm:text-5xl lg:text-6xl xl:text-7xl"
          >
            <span className="gradient-text2 lg:block">Talles</span>
            <span className="gradient-text lg:block">Furtado</span>
          </motion.h1>

          <motion.div variants={fadeUp} initial="hidden" animate="visible">
            <div className="mb-2 flex items-center gap-3">
              <FaDumbbell className="text-secondaryTheme h-6 w-6" />
              <h2 className="text-xl font-bold text-white sm:text-2xl lg:text-3xl">
                Especialista em Hipertrofia e Emagrecimento
              </h2>
            </div>
            <div className="h-8 overflow-hidden">
              <p className="text-mainTheme text-lg font-semibold transition-all duration-500 sm:text-xl">
                {texts[currentTextIndex]}
              </p>
            </div>
          </motion.div>

          <motion.p
            variants={slideUp}
            initial="hidden"
            animate="visible"
            className="text-base leading-relaxed text-white/80 sm:text-lg"
          >
            <strong>Bacharel em Educação Física</strong>, atleta de
            fisiculturismo e praticante há mais de <strong>10 anos</strong>.
            Dedico minha carreira a transformar vidas através do esporte,
            combinando ciência, experiência prática e acompanhamento
            personalizado.
          </motion.p>

          <motion.div
            variants={scaleIn}
            initial="hidden"
            animate="visible"
            className="grid grid-cols-2 gap-4 sm:grid-cols-3"
          >
            {stats.map((stat, index) => (
              <div
                key={stat.label}
                className="bg-navBlack/50 rounded-lg border border-white/10 p-4 text-center backdrop-blur-sm"
              >
                <div className="text-mainTheme mb-1 text-2xl font-bold">
                  {stat.value}
                </div>
                <div className="text-xs text-white/70">{stat.label}</div>
              </div>
            ))}
          </motion.div>

          <motion.div
            variants={slideUp}
            initial="hidden"
            animate="visible"
            className="flex flex-col gap-4 sm:flex-row"
          >
            <a
              href="#planos"
              className="group from-mainTheme hover:to-mainTheme shadow-mainTheme/30 flex items-center justify-center gap-3 rounded-xl bg-gradient-to-r to-blue-600 px-8 py-4 font-bold text-white shadow-lg transition-all duration-300 hover:from-blue-500"
            >
              <span>Ver Planos</span>
              <FiArrowRight className="h-5 w-5 transition-transform group-hover:translate-x-1" />
            </a>
            <a
              href="https://api.whatsapp.com/send/?phone=558198955665&text&type=phone_number&app_absent=0"
              target="_blank"
              rel="noopener noreferrer"
              className="group flex items-center justify-center gap-3 rounded-xl border border-green-500/30 bg-gradient-to-r from-green-600 to-green-500 px-8 py-4 font-bold text-white transition-all duration-300 hover:from-green-500 hover:to-green-400"
            >
              <FaWhatsapp className="text-2xl" />
              <span>Fale no WhatsApp</span>
            </a>
          </motion.div>
        </div>

        {/* Coluna direita - Imagem */}
        <div className="flex justify-center lg:w-1/2">
          <motion.div
            variants={scaleIn}
            initial="hidden"
            animate="visible"
            className="relative"
          >
            <div className="from-mainTheme to-secondaryTheme absolute inset-0 animate-pulse rounded-full bg-gradient-to-r opacity-20 blur-2xl" />
            <div className="border-mainTheme/30 animate-spin-slow absolute -inset-4 rounded-full border-2" />
            <Image
              src="/img/Img_Hero/profile2.png"
              alt="Talles Furtado - Personal Trainer"
              width={450}
              height={450}
              className="shadow-mainTheme/30 relative z-10 w-[280px] rounded-2xl border-4 border-white/10 shadow-2xl sm:w-[350px] lg:w-[450px]"
              priority
            />
            {/* Cards flutuantes */}
            <motion.div
              variants={slideUp}
              initial="hidden"
              animate="visible"
              className="bg-navBlack/80 absolute -bottom-6 -left-6 z-20 rounded-xl border border-white/10 p-4 shadow-xl backdrop-blur-sm"
            >
              <div className="flex items-center gap-3">
                <div className="bg-mainTheme/20 flex h-10 w-10 items-center justify-center rounded-full">
                  <FaDumbbell className="text-mainTheme h-5 w-5" />
                </div>
                <div>
                  <div className="font-bold text-white">+10 anos</div>
                  <div className="text-xs text-white/60">Experiência</div>
                </div>
              </div>
            </motion.div>
            <motion.div
              variants={slideUp}
              initial="hidden"
              animate="visible"
              className="bg-navBlack/80 absolute -top-6 -right-6 z-20 rounded-xl border border-white/10 p-4 shadow-xl backdrop-blur-sm"
            >
              <div className="flex items-center gap-3">
                <div className="bg-secondaryTheme/20 flex h-10 w-10 items-center justify-center rounded-full">
                  <FiAward className="text-secondaryTheme h-5 w-5" />
                </div>
                <div>
                  <div className="font-bold text-white">2x</div>
                  <div className="text-xs text-white/60">Campeão</div>
                </div>
              </div>
            </motion.div>
          </motion.div>
        </div>
      </div>

      {/* Scroll indicator */}
      <motion.div
        variants={fadeUp}
        initial="hidden"
        animate="visible"
        className="absolute bottom-8 left-1/2 -translate-x-1/2 transform"
      >
        <a
          href="#sobre"
          className="hover:text-mainTheme flex flex-col items-center text-white/60 transition-colors duration-300"
        >
          <span className="mb-2 text-sm">Saiba mais</span>
          <FiChevronDown className="h-6 w-6 animate-bounce" />
        </a>
      </motion.div>
    </section>
  );
}
