// app/components/Navbar.vue
<template>
  <nav
    class="fixed top-0 w-full z-40 bg-navBlack backdrop-blur-lg border-b-1 border-white/10"
  >
    <div class="max-w-5xl mx-auto px-4 p-3">
      <div class="flex justify-between items-center h-16">
        <!-- LOGO - Links para as imagens de logo -->
        <a href="#home">
          <!-- Logo para desktop -->
          <img
            src="/img/Logo/A10.png"
            alt="Logo Talles Furtado"
            class="hidden mobNav:block w-56"
            loading="lazy"
          />
          <!-- Logo para mobile -->
          <img
            src="/img/Logo/A4.png"
            alt="Logo Talles Furtado"
            class="w-13 block mobNav:hidden"
            loading="lazy"
          />
        </a>

        <!-- Container do ícone hamburguer (mobile) -->
        <div
          id="burger-zip"
          class="w-7 h-5 cursor-pointer z-40 lg:hidden"
          @click="$emit('toggleMenu')"
          aria-label="Abrir menu"
        >
          <Icon name="lucide:menu" size="30" />
        </div>

        <!-- Menu de navegação para desktop -->
        <div class="hidden lg:flex items-center space-x-8 font-extrabold">
          <!-- Links de navegação -->
          <a
            v-for="link in navLinks"
            :key="link.href"
            :href="link.href"
            class="text-gray-300 hover:text-gray-300 hover:drop-shadow-lg transition-all relative group py-2"
          >
            {{ link.label }}
            <!-- Efeito de underline animado -->
            <span
              class="absolute left-1/2 -bottom-0.5 w-0 h-0.5 bg-mainTheme group-hover:w-full transition-all duration-500 -translate-x-1/2"
            ></span>
          </a>
        </div>
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
// Define as props do componente
defineProps<{
  menuOpen: boolean;
}>();

// Define os eventos que o componente emite
defineEmits<{
  toggleMenu: [];
}>();

// Dados dos links de navegação
const navLinks = [
  { href: "#home", label: "Home" },
  { href: "#formacao", label: "Formação" },
  { href: "#beneficios", label: "Benefícios" },
  { href: "#planos", label: "Planos" },
  { href: "#resultados", label: "Resultados" },
  { href: "#conquistas", label: "Conquistas" },
  { href: "#feedback", label: "Feedback" },
];
</script>

// src/components/NavBar.tsx
"use client";

import Image from "next/image";
import NavLink from "@/components/NavLink";

/**
 * Navbar tradicional para telas grandes.
 *
 * No mobile ela é completamente ocultada. A navegação mobile foi deslocada
 * para uma barra fixa inferior para não ocupar espaço no topo da tela.
 */
export default function Navbar() {
  const navLinks = [
    { href: "#home", label: "Home", sectionId: "home" },
    { href: "#sobre", label: "Sobre", sectionId: "sobre" },
    { href: "#beneficios", label: "Benefícios", sectionId: "beneficios" },
    { href: "#planos", label: "Planos", sectionId: "planos" },
    { href: "#resultados", label: "Resultados", sectionId: "resultados" },
    { href: "#conquistas", label: "Conquistas", sectionId: "conquistas" },
    { href: "#feedback", label: "Feedback", sectionId: "feedback" },
    { href: "#time", label: "Time", sectionId: "time" },
  ];

  return (
    <nav className="bg-navBlack fixed top-0 z-40 hidden w-full border-b border-white/10 backdrop-blur-lg lg:block">
      <div className="mx-auto max-w-7xl px-4">
        <div className="flex h-16 items-center justify-between gap-8">
          {/* Logo desktop */}
          <a href="#home" className="flex shrink-0 items-center">
            <Image
              src="/img/Logo/A10.png"
              alt="Talles Furtado"
              width={224}
              height={56}
              className="h-12 w-auto"
              priority
            />
          </a>

          {/*
           * Os links observam o mesmo estado do Zustand usado pelo menu mobile.
           * Assim, somente a seção realmente visível recebe o destaque.
           */}
          <div className="flex min-w-0 items-center justify-end gap-5 font-extrabold xl:gap-7">
            {navLinks.map((link) => (
              <NavLink
                key={link.href}
                href={link.href}
                titulo={link.label}
                sectionId={link.sectionId}
              />
            ))}
          </div>
        </div>
      </div>
    </nav>
  );
}
